# Generated by Django 4.2.24 on 2026-07-18 07:55

from django.db import migrations, models
import django.db.models.deletion
import agentland.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission', models.TextField()),
                ('status', models.CharField(default='created', max_length=32)),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0)),
                ('token_limit', models.PositiveIntegerField(default=0)),
                ('cost_limit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='created', max_length=32)),
                ('acceptance_criteria', models.TextField()),
                ('artifact_reference', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('actor_id', models.CharField(blank=True, max_length=128)),
                ('public_summary', models.TextField()),
                ('structured_payload', agentland.models.JSONTextField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agentland.projectsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agentland.task')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
                ('status', models.CharField(default='idle', max_length=32)),
                ('public_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_workers', to='agentland.task')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='agentland.projectsession')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_estimated', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='agentland.workevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='agentland.projectsession')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='agentland.worker')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='agentland.worker'),
        ),
        migrations.AddField(
            model_name='task',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agentland.projectsession'),
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(default='running', max_length=32)),
                ('first_event_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('last_event_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('response_payload', agentland.models.JSONTextField(default=dict)),
                ('error_summary', models.TextField(blank=True)),
                ('runner_identity', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='agentland.projectsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentland.task')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=64)),
                ('relative_path', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('metadata', agentland.models.JSONTextField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agentland.projectsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agentland.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='agentland_session_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='dispatchrequest',
            constraint=models.UniqueConstraint(fields=('session', 'idempotency_key'), name='agentland_session_idempotency_unique'),
        ),
    ]
